FROM postgres

# need backports for openjdk package:
RUN echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/backports.list \
 && apt-get update \
 && apt-get -y install openjdk-11-jre curl

WORKDIR /usr/src/myapp

ARG FLUX_VERSION
ARG ARTIFACTORY_URL
ARG ARTIFACTORY_USER

# Use Curl to download with basic Auth and escape quotes to support passwords with special characters
RUN curl -u "${ARTIFACTORY_USER}" https://artifactory.portbase.io/artifactory/ext-release-local/io/flux-capacitor/flux-capacitor-service/${FLUX_VERSION}/flux-capacitor-service-${FLUX_VERSION}.jar --fail --output flux-capacitor-service.jar

ENV DROP_DATABASE false
ENTRYPOINT docker-entrypoint.sh postgres & sleep 1; java -DdropDatabase=$DROP_DATABASE -jar flux-capacitor-service.jar
