PUT {{baseUrl}}/_plugins/_security/api/roles/indices_full_access
Content-Type: application/json
Authorization: Basic root {{rootPassword}}

{
  "cluster_permissions": [
    "indices_all"
  ],
  "index_permissions": [
    {
      "index_patterns": [
        "*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "indices_all"
      ]
    }
  ]
}


###
PUT {{baseUrl}}/_plugins/_security/api/internalusers/auditlog
Content-Type: application/json
Authorization: Basic root {{rootPassword}}

{
  "password": "{{auditlogPassword}}",
  "opendistro_security_roles": ["indices_full_access"]
}


###
PUT {{baseUrl}}/_plugins/_security/api/rolesmapping/indices_full_access
Content-Type: application/json
Authorization: Basic root {{rootPassword}}

{
  "hosts" : [ "*" ],
  "users" : [ "auditlog" ]
}



###
PUT {{baseUrl}}/_index_template/trail
Content-Type: application/json
Authorization: Basic auditlog {{auditlogPassword}}

{
  "index_patterns": [
    "*trail*"
  ],
  "data_stream": {},
  "priority": 100,
  "template": {
    "settings": {
      "index": {
        "number_of_shards": 1,
        "number_of_replicas": 0
      },
      "analysis": {
        "analyzer": {
          "folding": {
            "tokenizer": "standard",
            "filter": [
              "lowercase",
              "asciifolding"
            ]
          }
        },
        "normalizer": {
          "lowerasciinormalizer": {
            "type": "custom",
            "filter": [
              "lowercase",
              "asciifolding"
            ]
          }
        }
      }
    },
    "mappings": {
      "dynamic_templates": [
        {
          "string_as_keyword": {
            "match_mapping_type": "string",
            "match": "*",
            "mapping": {
              "type": "keyword",
              "normalizer": "lowerasciinormalizer"
            }
          }
        }
      ]
    }
  }
}